export type animal = "Hedgehog" | "Dinosaur" | "Liger" | "Manatee" | "Dingo" | "Moose" | "Tiger" | "Walrus" | "Cormorant" | "Auroch" | "Coyote" | "Gopher" | "Leopard" | "Chipmunk" | "Panda" | "Rhino" | "Mink" | "Bat" | "Beaver" | "Narwhal" | "Kangaroo" | "Shrew" | "Wombat" | "Raccoon" | "Frog" | "Buffalo" | "Wolverine" | "Badger" | "Penguin" | "Pumpkin" | "Ibex" | "Alligator" | "Hippo" | "Anteater" | "Skunk" | "Sheep" | "Fox" | "Orangutan" | "Duck" | "Chupacabra" | "Camel" | "Python" | "Cheetah" | "Turtle" | "Wolf" | "Lemur" | "Ferret" | "Dolphin" | "Otter" | "Axolotl" | "Capybara" | "Iguana" | "Jackal" | "Chameleon" | "Grizzly" | "Quagga" | "Kraken" | "Chinchilla" | "Giraffe" | "Ifrit" | "Hyena" | "Rabbit" | "Platypus" | "Llama" | "Monkey" | "Elephant" | "Armadillo" | "Squirrel" | "Koala" | "Crow"
export const animal: animal[] = [
  "Hedgehog",
"Dinosaur",
"Liger",
"Manatee",
"Dingo",
"Moose",
"Tiger",
"Walrus",
"Cormorant",
"Auroch",
"Coyote",
"Gopher",
"Leopard",
"Chipmunk",
"Panda",
"Rhino",
"Mink",
"Bat",
"Beaver",
"Narwhal",
"Kangaroo",
"Shrew",
"Wombat",
"Raccoon",
"Frog",
"Buffalo",
"Wolverine",
"Badger",
"Penguin",
"Pumpkin",
"Ibex",
"Alligator",
"Hippo",
"Anteater",
"Skunk",
"Sheep",
"Fox",
"Orangutan",
"Duck",
"Chupacabra",
"Camel",
"Python",
"Cheetah",
"Turtle",
"Wolf",
"Lemur",
"Ferret",
"Dolphin",
"Otter",
"Axolotl",
"Capybara",
"Iguana",
"Jackal",
"Chameleon",
"Grizzly",
"Quagga",
"Kraken",
"Chinchilla",
"Giraffe",
"Ifrit",
"Hyena",
"Rabbit",
"Platypus",
"Llama",
"Monkey",
"Elephant",
"Armadillo",
"Squirrel",
"Koala",
"Crow"
]

export const color = {
  "Aqua": "#0000FF",
  "Blue": "#00bfff",
  "Red": "#FF0000",
  "Orange": "#FFC000",
  "Yellow": "#FFFC00",
  "Green": "#008000",
  "Cyan": "#00FFFF",
  "Magenta": "#FF0000",
}

export const colorArr = ["Aqua" , "Blue" , "Red" , "Orange" , "Yellow" , "Green" , "Cyan" , "Magenta"]
export type colors = "Aqua" | "Blue" | "Red" | "Orange" | "Yellow" | "Green" | "Cyan" | "Magenta"
export type colorObj = {
  Aqua: string,
  Blue: string,
  Red: string,
  Orange: string,
  Yellow: string,
  Green: string,
  Cyan: string,
  Magenta: string,
}